credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "git-credentials-goya"
              username: "porv-devgithub"
              password: "${GIT_PASSWORD_AFP}"
              description: "git-credentials-goya"
          - usernamePassword:
              scope: GLOBAL
              id: "github-emu"
              username: "devgithub_porvenir"
              password: "${GIT_PASSWORD_EMU}"
              description: "github-emu"
          - usernamePassword:
              scope: GLOBAL
              id: "az-login-goya"
              username: "00000000-0000-0000-0000-000000000000"
              password: "${AZ_LOGIN_PASSWORD_GOYA}"
              description: "az-login-goya"
          - usernamePassword:
              scope: GLOBAL
              id: "github-terraform"
              username: "PorvenirAFP"
              password: "${GIT_PASSWORD_AFP}"
              description: "github-terraform"
          - usernamePassword:
              scope: GLOBAL
              id: "github-terraform-emu"
              username: "PorvenirEMU"
              password: "${GIT_PASSWORD_EMU}"
              description: "github-terraform-emu"
          - usernamePassword:
              scope: GLOBAL
              id: "artifactory-cloud"
              username: "admin-cloud"
              password: "${ARTIFACTORY_CLOUD_PASSWORD}"
              description: "artifactory-cloud"
          - usernamePassword:
              scope: GLOBAL
              id: "artifactory-devops-jenkins"
              username: "devops_jenkins"
              password: "${ARTIFACTORY_DEVOPS_JENKINS}"
              description: "artifactory-devops-jenkins"
          - usernamePassword:
              scope: GLOBAL
              id: "artifactory-onpremise"
              username: "devops_ldap"
              password: "${ARTIFACTORY_JENKINS_ONPREMISE}"
              description: "artifactory-onpremise"
          - usernamePassword:
              scope: GLOBAL
              id: "influxdb"
              username: "devops"
              password: "${INFLUXDB_PASSWORD}"
              description: "influxdb"
          - string:
              scope: GLOBAL
              id: "sonarToken"
              secret: "${SONARQUBE_SECRET_TEXT}"
              description: "sonarToken"
          - string:
              scope: GLOBAL
              id: "sonarqube"
              secret: "${SONARQUBE_SECRET_TEXT2}"
              description: "sonarqube"
          - string:
              scope: GLOBAL
              id: "github-token"
              secret: "${GITHUB_TOKEN_SECRET_TEXT}"
              description: "github-token"
          - string:
              scope: GLOBAL
              id: "service-principal-devops"
              secret: "${AZ_SERVICE_PRINCIPAL_SECRET_TEXT}"
              description: "service-principal-devops"
          - string:
              scope: GLOBAL
              id: "tokenFortifyUp"
              secret: "${FORTIFY_TOKEN}"
              description: "tokenFortifyUp"
          - string:
              scope: GLOBAL
              id: "GITHUB_TOKEN_EMU"
              secret: "${GIT_PASSWORD_EMU}"
              description: "GITHUB_TOKEN_EMU"
          - aws:
              scope: GLOBAL
              id: "credentialaws"
              accessKey: "AKIAT2MKHTACNK6X2TWW"
              secretKey: "${AWS_SECRET_ACCESS_KEY}"
              description: "credentialaws"
          - string:
              scope: GLOBAL
              id: "fortify-temp-token-api"
              secret: "${FORTIFY_TEMP_TOKEN_API}"
              description: "fortify-temp-token-api"
          - string:
              scope: GLOBAL
              id: "fortify_token_download"
              secret: "${FORTIFY_TOKEN_DOWNLOAD}"
              description: "fortify_token_download"
          - string:
              scope: GLOBAL
              id: "azeupvgoyqastac_key"
              secret: "${GOYA_STORAGE_KEY_QA}"
              description: "azeupvgoyqastac_key"
          - string:
              scope: GLOBAL
              id: "jira-token"
              secret: "${JIRA_TOKEN}"
              description: "jira-token"
          - usernamePassword:
              scope: GLOBAL
              id: "GitHub"
              username: "porv-devgithub"
              password: "${GIT_PORV_DEVGITHUB}"
              description: "GitHub"
          - usernamePassword:
              scope: GLOBAL
              id: "user_so_multifondos"
              username: "wincpux"
              password: "${MULTIFONDOS_PASS}"
              description: "user_so_multifondos"
